channels:
- conda-forge
dependencies:
- python=3.10
- pip<=25.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.1
  - numpy==1.26.1
  - pandas==2.2.3
  - psutil==6.1.0
  - scikit-learn==1.6.1
  - scipy==1.15.3
  - flask
  - dagshub
  - prometheus_client
name: mlflow-env
